'use client';
import { useEffect, useState } from 'react';
import { useAuth } from '../lib/auth';

interface Item {
  id: number;
  title: string;
  description: string | null;
  completed: boolean;
}

export default function Home() {
  const { user, isAuthenticated, logout } = useAuth();
  const [items, setItems] = useState<Item[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch('/api/items')
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((data) => setItems(data))
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false));
  }, []);

  return (
    <>
      <header className="hero">
        {isAuthenticated && user && (
          <div className="auth-indicator">
            <span>{user.userDetails}</span>
            <a href="#" onClick={(e) => { e.preventDefault(); logout(); }}>Sign out</a>
          </div>
        )}
        <h1>azure-swa-nextjs-postgres</h1>
        <p className="subtitle">Your Azure full-stack app is ready.</p>
        <p className="generated-note">
          Generated by <strong>create-azure-app</strong> — a full-stack template
          preconfigured for Azure deployment with Static Web Apps + Functions + PostgreSQL.
        </p>
      </header>

      <div className="config-panel">
        <div className="config-card">
          <h2>Project Configuration</h2>
          <div className="config-grid">
            <div className="config-item">
              <span className="config-label">Framework</span>
              <span className="config-value">Next.js</span>
            </div>
            <div className="config-item">
              <span className="config-label">Database</span>
              <span className="config-value">Prisma</span>
            </div>
            <div className="config-item">
              <span className="config-label">Auth</span>
              <span className="config-value">Yes</span>
            </div>
            <div className="config-item">
              <span className="config-label">Tailwind</span>
              <span className="config-value">Yes</span>
            </div>
            <div className="config-item">
              <span className="config-label">Package Manager</span>
              <span className="config-value">npm</span>
            </div>
          </div>
        </div>
      </div>

      <div className="content">
        <section className="items-section">
          <h2>Using This Template</h2>
          <p className="items-note">Data in this list is loaded dynamically from your API</p>
          {loading && <p className="items-status">Loading items...</p>}
          {error && (
            <p className="items-status items-error">Could not load items: {error}</p>
          )}
          {!loading && !error && items.length === 0 && (
            <p className="items-status">
              No items yet. Run <code>npm run db:seed</code> to add sample data.
            </p>
          )}
          {items.length > 0 && (
            <ul className="items-grid">
              {items.map((item) => (
                <li key={item.id} className="item-card">
                  <span
                    className={`badge ${
                      item.completed ? 'badge-done' : 'badge-todo'
                    }`}
                  >
                    {item.completed ? 'Done' : 'Todo'}
                  </span>
                  <h3>{item.title}</h3>
                  {item.description && <p>{item.description}</p>}
                </li>
              ))}
            </ul>
          )}
        </section>
      </div>
    </>
  );
}
